#!/usr/bin/env python3
"""Bake TrueType faces into Adafruit-GFX bitmap fonts (1-bit, hinted MONO).

Why: on the GRAY4 e-paper panel, small text rendered by OpenFontRender (vector
+ 8-bit AA) is soft. A bitmap baked at the exact pixel height is grid-snapped
and crisp. Seeed_GFX renders GFXfont natively (TFT_eSPI drawChar), so these
headers drop straight into the existing setFreeFont() path.

Output: OpenSansGFX.h with 4 const GFXfont (Open Sans Regular 10/13, Bold 13/17)
matching TextRenderer facePx() for Sans7/Sans9/SansBold9/SansBold12.

Run:  python fonts/gen_gfx.py   (cwd = repo root or fonts/)
Deps: pip install freetype-py
"""
import os
import freetype

FIRST, LAST = 0x20, 0x7E  # printable ASCII

# Size ladder = union of the dashboard faces (10/13/17) and the Font Testing
# playground ladder (6,7,8,10,12,14,16,18,24,30,34). Regular + bold each.
# Symbols: OpenSans_R<px> / OpenSans_B<px>. faceGfx() uses R10/R13/B13/B17.
SIZES = [6, 7, 8, 10, 12, 13, 14, 16, 17, 18, 24, 30, 34]
FONTS = (
    [(f"OpenSans_R{px}", "OpenSans-Regular.ttf", px) for px in SIZES]
    + [(f"OpenSans_B{px}", "OpenSans-Bold.ttf", px) for px in SIZES]
    # Lexend: dashboard small faces only (Sans7=10, Sans9/SansBold9=13, SansBold12=17).
    + [
        ("Lexend_R10", "Lexend-Regular.ttf", 10),
        ("Lexend_R13", "Lexend-Regular.ttf", 13),
        ("Lexend_B13", "Lexend-Bold.ttf",    13),
        ("Lexend_B17", "Lexend-Bold.ttf",    17),
    ]
)

LOAD_FLAGS = freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO


class BitWriter:
    """Pack bits MSB-first; each glyph is flushed to a byte boundary (the
    Adafruit GFX format reads each glyph starting at a byte offset)."""
    def __init__(self):
        self.buf = bytearray()
        self.cur = 0
        self.n = 0

    def bit(self, b):
        self.cur = (self.cur << 1) | (b & 1)
        self.n += 1
        if self.n == 8:
            self.buf.append(self.cur)
            self.cur = 0
            self.n = 0

    def flush(self):
        if self.n:
            self.cur <<= (8 - self.n)
            self.buf.append(self.cur)
            self.cur = 0
            self.n = 0


def s8(v):
    """Clamp to signed 8-bit (xOffset/yOffset fields)."""
    return max(-128, min(127, v))


def bake(sym, ttf_path, px):
    face = freetype.Face(ttf_path)
    face.set_pixel_sizes(0, px)

    bitmaps = bytearray()
    glyphs = []  # (offset, w, h, xadv, xoff, yoff, code)

    for code in range(FIRST, LAST + 1):
        face.load_char(chr(code), LOAD_FLAGS)
        g = face.glyph
        bmp = g.bitmap                 # FT_PIXEL_MODE_MONO
        w, h, pitch = bmp.width, bmp.rows, bmp.pitch
        xadv = (g.advance.x + 32) >> 6  # 26.6 -> px, rounded
        xoff = s8(g.bitmap_left)
        yoff = s8(-g.bitmap_top)

        offset = len(bitmaps)
        if w and h:
            bw = BitWriter()
            data = bmp.buffer          # flat list, row-major, byte-padded rows
            for y in range(h):
                row = y * pitch
                for x in range(w):
                    byte = data[row + (x >> 3)]
                    bit = (byte >> (7 - (x & 7))) & 1
                    bw.bit(bit)
            bw.flush()
            bitmaps += bw.buf
        glyphs.append((offset, w, h, xadv, xoff, yoff, code))

    yadv = (face.size.height + 32) >> 6  # line advance, 26.6 -> px
    return bitmaps, glyphs, yadv


def emit(out, sym, bitmaps, glyphs, yadv):
    out.append(f"// {sym}: {len(glyphs)} glyphs, {len(bitmaps)} bitmap bytes")
    # bitmap array
    out.append(f"const uint8_t {sym}_Bitmaps[] PROGMEM = {{")
    line = "  "
    for i, b in enumerate(bitmaps):
        line += f"0x{b:02X},"
        if len(line) >= 96:
            out.append(line)
            line = "  "
    if line.strip():
        out.append(line)
    out.append("};")
    # glyph table
    out.append(f"const GFXglyph {sym}_Glyphs[] PROGMEM = {{")
    for (off, w, h, xadv, xoff, yoff, code) in glyphs:
        ch = chr(code) if code != 0x5C else "backslash"
        ch = ch if code not in (0x20,) else "space"
        out.append(f"  {{{off:5d},{w:3d},{h:3d},{xadv:3d},{xoff:4d},{yoff:4d}}},  // 0x{code:02X} {ch}")
    out.append("};")
    # font struct (cast away const to match Adafruit GFXfont signature)
    out.append(
        f"const GFXfont {sym} PROGMEM = {{"
        f"(uint8_t*){sym}_Bitmaps,(GFXglyph*){sym}_Glyphs,"
        f"0x{FIRST:02X},0x{LAST:02X},{yadv}}};"
    )
    out.append("")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = [
        "// Generated by fonts/gen_gfx.py - do not edit by hand.",
        "// Baked bitmap faces (Open Sans full ladder + Lexend small) - 1-bit MONO, crisp small text.",
        "// GFXglyph/GFXfont come from TFT_eSPI (include this AFTER the display header).",
        "#pragma once",
        "",
    ]
    for sym, ttf, px in FONTS:
        path = os.path.join(here, ttf)
        bitmaps, glyphs, yadv = bake(sym, path, px)
        emit(out, sym, bitmaps, glyphs, yadv)
        print(f"{sym:14s} px={px:2d} glyphs={len(glyphs)} bytes={len(bitmaps):5d} yAdvance={yadv}")

    # Emit at the sketch root (sibling of FontData.h) so the Arduino build finds it.
    hpath = os.path.join(os.path.dirname(here), "OpenSansGFX.h")
    with open(hpath, "w", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {hpath}")


if __name__ == "__main__":
    main()
